### ISSUE TITLE
Undefined symbol `_ZN6google8protobuf2io17SafeDoubleToFloatEd`

### ISSUE THREAD

**Issue by xylar** [conda-forge/protobuf-feedstock#190]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This may be an upstream issue but I want to check here first.

In downstream packages I'm seeing an undefined symbol error (e.g. in https://github.com/conda-forge/google-cloud-workflows-feedstock/pull/25).  I can reproduce this with both 4.23.1 and 4.23.2 releases:
```
$ mamba create -y -n test protobuf=4.23.2 libprotobuf=4.23.2
$ mamba activate test
$ python -c "from google.protobuf import descriptor"
/home/xylar/mambaforge/envs/test/lib/python3.11/site-packages/google/protobuf/internal/api_implementation.py:110: UserWarning: Selected implementation cpp is not available.
  warnings.warn(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xylar/mambaforge/envs/test/lib/python3.11/site-packages/google/protobuf/descriptor.py", line 51, in <module>
    from google.protobuf.pyext import _message
ImportError: /home/xylar/mambaforge/envs/test/lib/python3.11/site-packages/google/protobuf/pyext/_message.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN6google8protobuf2io17SafeDoubleToFloatEd
```

### Installed packages

```shell
$ mamba list
# packages in environment at /home/xylar/mambaforge/envs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2023.5.7             hbcca054_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libabseil                 20230125.2      cxx17_h59595ed_2    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libprotobuf               4.23.2               hd1fb520_1    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   3.1.0                hd590300_3    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
protobuf                  4.23.2          py311hbec7ed6_0    conda-forge
python                    3.11.3          h2755cc3_0_cpython    conda-forge
python_abi                3.11                    3_cp311    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
```

### Environment info

```shell
$ mamba info

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


     active environment : test
    active env location : /home/xylar/mambaforge/envs/test
            shell level : 2
       user config file : /home/xylar/.condarc
 populated config files : /home/xylar/mambaforge/.condarc
                          /home/xylar/.condarc
          conda version : 23.3.1
    conda-build version : 3.24.0
         python version : 3.10.11.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=5.19.0=0
                          __unix=0=0
       base environment : /home/xylar/mambaforge  (writable)
      conda av data dir : /home/xylar/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/xylar/mambaforge/pkgs
                          /home/xylar/.conda/pkgs
       envs directories : /home/xylar/mambaforge/envs
                          /home/xylar/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.29.0 CPython/3.10.11 Linux/5.19.0-42-generic ubuntu/22.04.2 glibc/2.35
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

**Comment by xylar** [comment]
@h-vetinari, I know you're working hard on migrations of abseil / grpc / protobuf.  I wanted to check with you to see if you had any insight on this particular issue, in case it is something you came across in your testing.

**Comment by h-vetinari** [comment]
Ugh, apparently our tests didn't catch this (and there's a difference between `import google.protobuf` and `from google.protobuf import descriptor`) 😑
