### ISSUE TITLE
gdal stack: cannot open libabsl_cord.so.2301.0.0

### ISSUE THREAD

**Issue by mathause** [conda-forge/protobuf-feedstock#198]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The newest release of protopuf seems to lead to a failed gdal stack. It is very likely that this is an upstream issue and this is the wrong place to report this. I still wanted to report it as a cursory search has not shown anything.

Importing `rasterio`, `fiona`, or `pyogrio` all fail with `ImportError: libabsl_cord.so.2301.0.0: cannot open shared object file: No such file or directory`. I think it's a protobuf problem because `import rasterio` fails for:

```bash
mamba create -n protobuf_error rasterio
```
but works for
```bash
mamba create -n protobuf_no_error rasterio "libprotobuf<4.23.4"
```

The dependency goes like `rasterio -> libgdal -> tiledb -> libgoogle-cloud -> libgrpc -> libprotobuf`

The tracepacks for are similar for `rasterio`, `fiona`, and `pyogrio`:

```python-traceback
>>> import rasterio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mathause/.conda/envs/protobuf_error/lib/python3.11/site-packages/rasterio/__init__.py", line 28, in <module>
    from rasterio._version import gdal_version, get_geos_version, get_proj_version
ImportError: libabsl_cord.so.2301.0.0: cannot open shared object file: No such file or directory
```

### Installed packages

<details>

```shell
# packages in environment at /home/mathause/.conda/envs/protobuf_error:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
affine                    2.4.0              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
blosc                     1.21.5               h0f2a231_0    conda-forge
boost-cpp                 1.78.0               h2c5509c_4    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cairo                     1.16.0            h0c91306_1017    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cfitsio                   4.3.0                hbdc6101_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
expat                     2.5.0                hcb278e6_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
freexl                    1.0.6                h166bdaf_1    conda-forge
geos                      3.12.0               h59595ed_0    conda-forge
geotiff                   1.7.1               h22adcc9_11    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
giflib                    5.2.1                h0b41bf4_3    conda-forge
gtest                     1.14.0               h00ab1b0_1    conda-forge
hdf4                      4.2.15               h501b40f_6    conda-forge
hdf5                      1.14.2          nompi_h4f84152_100    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
json-c                    0.17                 h7ab15ed_0    conda-forge
kealib                    1.5.1                hcd42e92_5    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
lcms2                     2.15                 haa2dc70_1    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20230802.0      cxx17_h59595ed_3    conda-forge
libaec                    1.0.6                hcb278e6_1    conda-forge
libarchive                3.6.2                h039dbb9_1    conda-forge
libblas                   3.9.0           18_linux64_openblas    conda-forge
libcblas                  3.9.0           18_linux64_openblas    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcurl                   8.2.1                hca28451_0    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_0    conda-forge
libgdal                   3.7.1                h880a63b_9    conda-forge
libgfortran-ng            13.2.0               h69a702a_0    conda-forge
libgfortran5              13.2.0               ha4646dd_0    conda-forge
libglib                   2.78.0               hebfc3b9_0    conda-forge
libgomp                   13.2.0               h807b86a_0    conda-forge
libgoogle-cloud           2.12.0               h8d7e28b_2    conda-forge
libgrpc                   1.57.0               ha4d0f93_1    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
libkml                    1.3.0             h37653c0_1015    conda-forge
liblapack                 3.9.0           18_linux64_openblas    conda-forge
libnetcdf                 4.9.2           nompi_h80fb2b6_112    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.24          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libpq                     15.4                 hfc447b1_0    conda-forge
libprotobuf               4.23.4               hf27288f_5    conda-forge
librttopo                 1.1.0               hb58d41b_14    conda-forge
libspatialite             5.0.1               h15f6e67_28    conda-forge
libsqlite                 3.43.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_0    conda-forge
libtiff                   4.5.1                h8b53f26_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.1                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxml2                   2.11.5               h232c23b_1    conda-forge
libzip                    1.10.1               h2629f0a_3    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
nspr                      4.35                 h27087fc_0    conda-forge
nss                       3.92                 h1d7d5a4_0    conda-forge
numpy                     1.25.2          py311h64a7726_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.1.2                hd590300_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
poppler                   23.08.0              hd18248d_0    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                15.4                 h8972f4a_0    conda-forge
proj                      9.2.1                ha643af7_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
python                    3.11.5          hab00c5b_0_cpython    conda-forge
python_abi                3.11                    3_cp311    conda-forge
rasterio                  1.3.8           py311h41e4db2_0    conda-forge
re2                       2023.03.02           h8c504da_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                68.1.2             pyhd8ed1ab_0    conda-forge
snappy                    1.1.10               h9fff704_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sqlite                    3.43.0               h2c6b66d_0    conda-forge
tiledb                    2.16.3               h84d19f0_1    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tzcode                    2023c                h0b41bf4_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.4                hac6953d_3    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.6                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```
</details>

### Environment info

<details>

```shell
active environment : protobuf_error
    active env location : /home/mathause/.conda/envs/protobuf_error
            shell level : 2
       user config file : /home/mathause/.condarc
 populated config files : /home/mathause/.mambabase/.condarc
                          /home/mathause/.condarc
          conda version : 23.7.3
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=6.2.0=0
                          __unix=0=0
       base environment : /home/mathause/.mambabase  (writable)
      conda av data dir : /home/mathause/.mambabase/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/mathause/.conda/pkgs
                          /home/mathause/.mambabase/pkgs
       envs directories : /home/mathause/.conda/envs
                          /home/mathause/.mambabase/envs
               platform : linux-64
             user-agent : conda/23.7.3 requests/2.31.0 CPython/3.10.12 Linux/6.2.0-32-generic linuxmint/21.1 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

</details>

**Comment by h-vetinari** [comment]
It appears something in the gdal stack depends on abseil these days, but that this is not reflected in the metadata (and therefore not our rebuilds). The reason it broke with protobuf 4.23.4 is because we bumped abseil with that version, and the `so.2301.0.0` refers to the previous abseil version.

Could you check through the dependent recipes between {rasterio, fiona, pyogrio} and protobuf where in the build logs there's from the latest builds on the main branch there's a warning along the lines of:
```
WARNING (packagename,lib/libsomething.lib): lib/libabsl_cord.do not found in any packages
```
?

**Comment by mathause** [comment]
That seems to work again. Thanks for figuring out the root cause - that was definitely above my current knowledge!
